version: '2'
services:
  rabbitmq:
    image: rabbitmq
    restart: always
  mysql:
    image: mysql
    restart: always
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=eq8"
  redis:
    image: redis
    restart: always
  elasticsearch:
    image: elasticsearch
    restart: always
  proxy:
    build: services/proxy
    image: eq8/proxy
    restart: always
    ports:
     - "80:80"
    links:
     - assets
     - logic
  assets:
    build: services/assets
    image: eq8/assets
    restart: always
  logic:
    build: services/logic
    image: eq8/logic
    restart: always
    links:
      - rabbitmq
      - elasticsearch
  vcs:
    build: services/vcs
    image: eq8/vcs
    restart: always
    links:
     - mysql
     - rabbitmq
     - redis
  indexer:
    build: services/indexer
    image: eq8/indexer
    restart: always
    links:
     - redis
     - elasticsearch
