version: '2'
services:
  beanstalkd:
    image: bbartolome/beanstalkd
    restart: always
  elasticsearch:
    image: elasticsearch
    restart: always
  redis:
    image: redis
    restart: always
  mysql:
    image: mysql
    restart: always
    environment:
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
  proxy:
    build: services/proxy
    image: eq8/proxy
    restart: always
    ports:
     - "80:80"
    links:
     - gateway
     - processor
  gateway:
    build: services/gateway
    image: eq8/gateway
    restart: always
    links:
      - beanstalkd
      - elasticsearch
      - redis
  processor:
    build: services/processor
    image: eq8/processor
    restart: always
    links:
      - beanstalkd
      - mysql
  indexer:
    build: services/indexer
    image: eq8/indexer
    restart: always
    links:
      - redis
      - mysql
      - elasticsearch
  notifier:
    build: services/notifier
    image: eq8/notifier
    restart: always
    links:
      - mysql
      - redis
